global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    basic_auth:
      username: "2860455"              # Prometheus Instance ID
      password: "<GRAFANA_API_KEY>"    # MetricsPublisher key

scrape_configs:
  - job_name: "Setupathi School App"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3001"]
        labels:
          app: "ems-frontend"
