// Service Worker for Setupati School Management System PWA
// Integrated with Vite PWA Plugin using injectManifest strategy

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import {
  CacheFirst,
  NetworkFirst,
  StaleWhileRevalidate
} from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: any;
  skipWaiting(): void;
  clients: Clients;
  registration: ServiceWorkerRegistration;
};

const SW_VERSION = '2.1.0';

// Precache all static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up outdated caches
cleanupOutdatedCaches();

// Cache configuration
const CACHE_CONFIG = {
  static: {
    name: `setupati-school-static-v${SW_VERSION}`,
    maxEntries: 100,
    maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
  },
  dynamic: {
    name: `setupati-school-dynamic-v${SW_VERSION}`,
    maxEntries: 50,
    maxAgeSeconds: 60 * 60 * 24 * 7 // 7 days
  },
  api: {
    name: `setupati-school-api-v${SW_VERSION}`,
    maxEntries: 100,
    maxAgeSeconds: 60 * 5, // 5 minutes
    networkTimeoutSeconds: 3
  },
  images: {
    name: `setupati-school-images-v${SW_VERSION}`,
    maxEntries: 200,
    maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
  }
};

// Google Fonts caching
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

// API caching with network-first strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: CACHE_CONFIG.api.name,
    networkTimeoutSeconds: CACHE_CONFIG.api.networkTimeoutSeconds,
    plugins: [
      new ExpirationPlugin({
        maxEntries: CACHE_CONFIG.api.maxEntries,
        maxAgeSeconds: CACHE_CONFIG.api.maxAgeSeconds
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

// Image caching with cache-first strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: CACHE_CONFIG.images.name,
    plugins: [
      new ExpirationPlugin({
        maxEntries: CACHE_CONFIG.images.maxEntries,
        maxAgeSeconds: CACHE_CONFIG.images.maxAgeSeconds
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

// Navigation requests with stale-while-revalidate
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new StaleWhileRevalidate({
    cacheName: CACHE_CONFIG.dynamic.name,
    plugins: [
      new ExpirationPlugin({
        maxEntries: CACHE_CONFIG.dynamic.maxEntries,
        maxAgeSeconds: CACHE_CONFIG.dynamic.maxAgeSeconds
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

// Enhanced background sync for offline actions
self.addEventListener('sync', (event: ExtendableEvent & { tag: string }) => {
  console.log('Service Worker: Background sync triggered', event.tag);

  if (event.tag === 'background-sync') {
    event.waitUntil(doBackgroundSync());
  } else if (event.tag.startsWith('sync-')) {
    // Handle specific sync operations
    event.waitUntil(handleSpecificSync(event.tag));
  }
});

async function doBackgroundSync() {
  try {
    console.log('Service Worker: Performing background sync');

    // Perform offline data synchronization
    const syncResult = await performOfflineDataSync();

    // Notify clients that sync completed
    const clients = await self.clients.matchAll();
    clients.forEach((client) => {
      client.postMessage({
        type: 'SYNC_COMPLETE',
        timestamp: Date.now(),
        syncResult: syncResult
      });
    });

    console.log('Service Worker: Background sync completed successfully');
  } catch (error) {
    console.error('Service Worker: Background sync failed', error);

    // Notify clients of sync failure
    const clients = await self.clients.matchAll();
    clients.forEach((client) => {
      client.postMessage({
        type: 'SYNC_FAILED',
        timestamp: Date.now(),
        error: error instanceof Error ? error.message : 'Unknown error'
      });
    });
  }
}

async function handleSpecificSync(tag: string) {
  console.log(`Service Worker: Handling specific sync: ${tag}`);

  try {
    if (tag === 'sync-attendance') {
      await syncSpecificData('attendance');
    } else if (tag === 'sync-timetables') {
      await syncSpecificData('timetables');
    } else if (tag === 'sync-results') {
      await syncSpecificData('results');
    } else if (tag === 'sync-circulars') {
      await syncSpecificData('circulars');
    } else if (tag === 'sync-profiles') {
      await syncSpecificData('profiles');
    }
  } catch (error) {
    console.error(`Service Worker: Specific sync failed for ${tag}`, error);
  }
}

// Perform offline data synchronization
async function performOfflineDataSync() {
  const syncResult = {
    success: true,
    syncedItems: 0,
    failedItems: 0,
    errors: [] as string[]
  };

  try {
    // Open IndexedDB
    const db = await openOfflineDB();

    // Get sync queue
    const syncQueue = await getAllFromStore(db, 'syncQueue');
    console.log(
      `Service Worker: Found ${syncQueue.length} items in sync queue`
    );

    // Process sync queue items
    for (const item of syncQueue) {
      try {
        const success = await processSyncItem(item);
        if (success) {
          syncResult.syncedItems++;
          await deleteFromStore(db, 'syncQueue', item.id);
        } else {
          syncResult.failedItems++;
          await updateSyncItemRetryCount(db, item);
        }
      } catch (error) {
        syncResult.failedItems++;
        syncResult.errors.push(
          `${item.endpoint}: ${error instanceof Error ? error.message : 'Unknown error'}`
        );
        await updateSyncItemRetryCount(db, item);
      }
    }

    // Sync unsynced data from stores
    await syncUnsyncedDataFromStores(db, syncResult);

    db.close();
    return syncResult;
  } catch (error) {
    console.error('Service Worker: Offline data sync failed', error);
    syncResult.success = false;
    syncResult.errors.push(
      error instanceof Error ? error.message : 'Unknown error'
    );
    return syncResult;
  }
}

// Open IndexedDB connection
function openOfflineDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('setupati-school-offline', 2);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

// Get all items from a store
function getAllFromStore(db: IDBDatabase, storeName: string): Promise<any[]> {
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([storeName], 'readonly');
    const store = transaction.objectStore(storeName);
    const request = store.getAll();
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

// Delete item from store
function deleteFromStore(
  db: IDBDatabase,
  storeName: string,
  key: string
): Promise<void> {
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([storeName], 'readwrite');
    const store = transaction.objectStore(storeName);
    const request = store.delete(key);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
  });
}

// Update sync item retry count
async function updateSyncItemRetryCount(db: IDBDatabase, item: any) {
  const updatedItem = {
    ...item,
    retryCount: item.retryCount + 1,
    lastError: 'Sync failed'
  };

  if (updatedItem.retryCount >= item.maxRetries) {
    // Remove item if max retries reached
    await deleteFromStore(db, 'syncQueue', item.id);
    console.log(
      `Service Worker: Removed sync item ${item.id} after max retries`
    );
  } else {
    // Update retry count
    const transaction = db.transaction(['syncQueue'], 'readwrite');
    const store = transaction.objectStore('syncQueue');
    store.put(updatedItem);
  }
}

// Process individual sync item
async function processSyncItem(item: any): Promise<boolean> {
  try {
    const method = getHttpMethod(item.action);
    const options: RequestInit = {
      method,
      headers: {
        'Content-Type': 'application/json'
      }
    };

    if (item.action !== 'DELETE' && item.data) {
      options.body = JSON.stringify(item.data);
    }

    const response = await fetch(item.endpoint, options);

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    console.log(
      `Service Worker: Successfully synced ${item.action} for ${item.endpoint}`
    );
    return true;
  } catch (error) {
    console.error(
      `Service Worker: Failed to sync ${item.action} for ${item.endpoint}`,
      error
    );
    return false;
  }
}

// Get HTTP method for sync action
function getHttpMethod(action: string): string {
  switch (action) {
    case 'CREATE':
      return 'POST';
    case 'UPDATE':
      return 'PUT';
    case 'DELETE':
      return 'DELETE';
    default:
      return 'POST';
  }
}

// Sync unsynced data from local stores
async function syncUnsyncedDataFromStores(db: IDBDatabase, syncResult: any) {
  const stores = [
    'attendance',
    'timetables',
    'results',
    'circulars',
    'userProfile'
  ];

  for (const storeName of stores) {
    try {
      const unsyncedItems = await getUnsyncedItems(db, storeName);

      for (const item of unsyncedItems) {
        try {
          await syncDataItem(storeName, item);
          await markItemAsSynced(db, storeName, item.id);
          syncResult.syncedItems++;
        } catch (error) {
          syncResult.failedItems++;
          syncResult.errors.push(
            `${storeName} sync failed: ${error instanceof Error ? error.message : 'Unknown error'}`
          );
        }
      }
    } catch (error) {
      console.error(`Service Worker: Failed to sync ${storeName}`, error);
      syncResult.errors.push(
        `${storeName} sync failed: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }
}

// Get unsynced items from store
function getUnsyncedItems(db: IDBDatabase, storeName: string): Promise<any[]> {
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([storeName], 'readonly');
    const store = transaction.objectStore(storeName);

    // Check if the 'synced' index exists
    try {
      const index = store.index('synced');
      const request = index.getAll(IDBKeyRange.only(false));
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    } catch (error) {
      // If index doesn't exist, get all items and filter
      const request = store.getAll();
      request.onsuccess = () => {
        const items = request.result.filter((item: any) => !item.synced);
        resolve(items);
      };
      request.onerror = () => reject(request.error);
    }
  });
}

// Sync individual data item
async function syncDataItem(storeName: string, item: any) {
  const endpointMap: Record<string, string> = {
    attendance: '/api/attendance',
    timetables: '/api/timetable',
    results: '/api/examresult',
    circulars: '/api/circular',
    userProfile: '/api/user'
  };

  const endpoint = `${endpointMap[storeName]}/${item.id}`;

  const response = await fetch(endpoint, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(item)
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }
}

// Mark item as synced
function markItemAsSynced(
  db: IDBDatabase,
  storeName: string,
  itemId: string
): Promise<void> {
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([storeName], 'readwrite');
    const store = transaction.objectStore(storeName);
    const getRequest = store.get(itemId);

    getRequest.onsuccess = () => {
      const item = getRequest.result;
      if (item) {
        item.synced = 1; // 1 = true for IndexedDB compatibility
        const putRequest = store.put(item);
        putRequest.onsuccess = () => resolve();
        putRequest.onerror = () => reject(putRequest.error);
      } else {
        resolve();
      }
    };

    getRequest.onerror = () => reject(getRequest.error);
  });
}

// Sync specific data type
async function syncSpecificData(dataType: string) {
  try {
    const db = await openOfflineDB();
    const syncResult = {
      syncedItems: 0,
      failedItems: 0,
      errors: [] as string[]
    };

    const storeMap: Record<string, string> = {
      attendance: 'attendance',
      timetables: 'timetables',
      results: 'results',
      circulars: 'circulars',
      profiles: 'userProfile'
    };

    const storeName = storeMap[dataType];
    if (storeName) {
      const unsyncedItems = await getUnsyncedItems(db, storeName);

      for (const item of unsyncedItems) {
        try {
          await syncDataItem(storeName, item);
          await markItemAsSynced(db, storeName, item.id);
          syncResult.syncedItems++;
        } catch (error) {
          syncResult.failedItems++;
          syncResult.errors.push(
            error instanceof Error ? error.message : 'Unknown error'
          );
        }
      }
    }

    db.close();

    // Notify clients of specific sync completion
    const clients = await self.clients.matchAll();
    clients.forEach((client) => {
      client.postMessage({
        type: 'SPECIFIC_SYNC_COMPLETE',
        dataType: dataType,
        syncResult: syncResult,
        timestamp: Date.now()
      });
    });
  } catch (error) {
    console.error(
      `Service Worker: Specific sync failed for ${dataType}`,
      error
    );
  }
}

// Enhanced push notification handling
self.addEventListener('push', (event: PushEvent) => {
  console.log('Service Worker: Push notification received');

  let notificationData: NotificationOptions & { title: string } = {
    title: 'Setupati School',
    body: 'You have new updates from Setupati School',
    icon: '/school.png',
    badge: '/school.png',
    vibrate: [100, 50, 100],
    data: {
      dateOfArrival: Date.now(),
      primaryKey: 1
    },
    actions: [
      {
        action: 'explore',
        title: 'View Details',
        icon: '/school.png'
      },
      {
        action: 'close',
        title: 'Close',
        icon: '/school.png'
      }
    ],
    requireInteraction: false,
    silent: false
  };

  if (event.data) {
    try {
      const data = event.data.json();
      notificationData = {
        ...notificationData,
        title: data.title || notificationData.title,
        body: data.body || notificationData.body,
        icon: data.icon || notificationData.icon,
        data: { ...notificationData.data, ...data.data },
        tag: data.tag || 'default',
        requireInteraction: data.requireInteraction || false
      };
    } catch (error) {
      console.error('Service Worker: Failed to parse push data', error);
    }
  }

  event.waitUntil(
    self.registration.showNotification(notificationData.title, notificationData)
  );
});

// Enhanced notification click handling
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('Service Worker: Notification clicked', event.action);

  event.notification.close();

  const action = event.action;
  const data = event.notification.data;

  event.waitUntil(
    (async () => {
      const clients = await self.clients.matchAll({ type: 'window' });

      if (action === 'close') {
        return; // Just close the notification
      }

      // Default action or 'explore' action
      const urlToOpen = data?.url || '/';

      // Check if app is already open
      for (const client of clients) {
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return (client as WindowClient).focus();
        }
      }

      // Open new window/tab
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })()
  );
});

// Handle messages from clients
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('Service Worker: Message received', event.data);

  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (event.data && event.data.type === 'GET_VERSION') {
    event.ports[0].postMessage({ version: SW_VERSION });
  } else if (event.data && event.data.type === 'CACHE_STATS') {
    getCacheStats().then((stats) => {
      event.ports[0].postMessage(stats);
    });
  }
});

// Get cache statistics
async function getCacheStats(): Promise<Record<string, any>> {
  const stats: Record<string, any> = {};

  for (const [key, config] of Object.entries(CACHE_CONFIG)) {
    try {
      const cache = await caches.open(config.name);
      const keys = await cache.keys();
      stats[key] = {
        name: config.name,
        entries: keys.length,
        maxEntries: config.maxEntries
      };
    } catch (error) {
      stats[key] = {
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  return stats;
}

console.log(
  `Service Worker v${SW_VERSION} loaded successfully with Vite PWA integration`
);
